### PR TITLE
simple changes needed for python3

### PR DESCRIPTION
**Pull request by bjorns163**
added the simple changes in print command for python 3 to heko you with you #12 port to python3

### CODE REVIEW

**Comment by ickerwx** [comment]
Hey, thank you so much for taking the time and helping me with this. I would have gotten around to it myself eventually but not as quickly as you. I really appreciate it.

The use of `print` as a function instead of a statement is certainly one of the biggest changes, but there are a couple more things that need to be done. Right now I am basically concatenating strings everywhere (kind of a cheap and hacky solution in itself), but this will not work in python3 because what was a string in py2 is often a bytes object in py3.

I will very gladly take your contribution as a base to start the rest of the port, your PR did a lot of the work. As soon as I find the time to do this I will merge your changes into a new py3 branch.

Again, I honestly appreciate that you spent your time on this and I will definitely use your changes, but I'm not gonna merge them into `master` just now because the port is not complete. I will however keep this PR open until then.

Thanks a lot.

**Comment by bjorns163** [comment]
Hey,

No worries i understaand just made a few more changes to get the port complete still testing here. hope it helps you.

**Comment by bjorns163** [comment]
ok this should be the working version. I have been testing with python 3.7.6 and 3.6.8

**Comment by ickerwx** [comment]
I have merged some of your changes into a temporary branch to test them out. Allow me to give you a little feedback on your work.

Let me start by saying thank you again for spending your time on this, it's is highly appreciated. I have a couple of issues, though, and stopped cherry-picking your commits somewhere in the middle.

I believe you should try to make smaller pull requests. It is a lot easier to just skim a PR where basically every change is the same. like moving from `print` statement to function. I can skim over this, see it works, and merge it.

You make several changes to several files in one PR, you also introduce bugs in one commit that are then fixed again in a later commit. Don't do that, it makes reviewing your pull requests unnecessarily hard.

Your `ipfilter` module is a nice idea and I will maybe later introduce a similar feature, but a proxy module is the wrong place to implement an IP blacklist. Usually you shouldn't even need this because you control who connects to the proxy. And in the cases you don't, `iptables` is what you probably want.

Thanks a lot for your work. I will use some of your work and leave some of it out, and I will now close this pull request. I will of course make sure to credit you in the contributors section of the README once I'm done.

**Pull request closed without merging**
