### PR TITLE
Socks proxy for tcpproxy listener

### PR DESCRIPTION
**Pull request by ptitdoc**
Experiment usage of others protocols than TCP:
- Initial SOCKS implementation for incoming traffic
- Planned implementation of UDP (and SOCKS-UDP?)

Implementation of HTTP-Proxy is not foreseen as this feature it is not very interesting compared to existing HTTP proxies.

### CODE REVIEW

**Comment by ptitdoc** [comment]
Just found implementation from https://github.com/shunf4/tcpproxy/tree/for_upstream
https://github.com/ickerwx/tcpproxy/issues/24

I will check if there is additionnal things that can be imported from his code.

**Comment by ickerwx** [comment]
I have merged this and #27 into the branch ptitdoc-ethicomputing-merge. Right now it looks like there are a few bugs that need to be dealt with, and to be honest I still need to re-read some of the changes.

So far it's looking pretty good function-wise, although I'm having trouble with running mitm against TLS, I'll have to look into this. Please merge additional PR's into the branch mentioned above for now, not master.

Thanks for your time, Olivier.

**Comment by ptitdoc** [comment]
Do not hesitate for help with TLS. Normally sslupgrade module without any option should suffice. However if you want to deal with SNI you have to enable peek_sni before.

**Comment by davidmann4** [comment]
hmm, is this related to issue #29 ?

I tried your code and it also did not worked for my application. Let me know if I can help somehow.

**Pull request closed without merging**
