### PR TITLE
Rewrite TCPProxy plugin mechanism

### PR DESCRIPTION
**Pull request by ptitdoc**
Hello,

This pull request is only for documentation purpose for now as it has been forked and is now out of sync with the tcpproxy master branch. This is an attempt to update TCPProxy with several features including:
- pushing as much code as possible into plugins (ssl, proxy ...)
- implementing a client/server API through redis
- implementing a CLI/GUI client allowing to inspect and edit packets
- adding more options to SSL plugin for client certificate inspection and man-in-the-middle

### CODE REVIEW

**Comment by ptitdoc** [comment]
There are still some work to be done, especially related to:
- move redis code outside tcpproxy.py
- more and uptodate documentation
- finalise the inspection plugin
- rewrite the python ssl library patch for python3 for client certificate inspection
- implement logging through redis

**Comment by ickerwx** [comment]
Olivier, thanks again for spending so much time and energy on adding such a load of cool features to the proxy. During the last couple of weeks I have been trying to find a day or to to actually play with your changes and try to merge them in, but I'm afraid that right now I am just too occupied to properly review everything.

If it's alright with you I will keep the PR open for the time being, like some kind of constantly nagging reminder that there is work to be done.

**Comment by ptitdoc** [comment]
Hello,

No problem, I'm commiting some fixes from time to time as I'm using it quite often. I'm also missing one major feature that needs to be commited (simple code however) to perform packet inspection/edition.

I also try from time to time to check your master branch to merge new features / fixes into my branch.

**Comment by wildstray** [comment]
@ptitdoc please check #26 I suggested a PR for specific purposes (OT security), but we made similar changes and might be useful for us to check both PRs.

**Comment by ptitdoc** [comment]
Hello,
Looks interresting. I will take a look to see how I can merge.

**Comment by ptitdoc** [comment]
It may be feasible to merge with my code:
- Logging is not finalized for in my code base as some logs are not going to redis (in order to get error feedback through the GUI such as server not reachable or invalid plugin parameters)
- Their DROP/REJECT can be implemented as plugins (I already have a drop plugin but I will check their as they are apparently doing more things)
- Their rules is not far away from me, I through about loading rules as flat files instead of redis but never implemented it, so I should be easy to do so. However their logic for filtering is different as they have different parameters. I need to think about that.

**Pull request closed without merging**
